### ISSUE TITLE
Dictionary Keys not sorted alphabetically

### ISSUE THREAD

**Issue by ArchRBX** [pinehappi/DataDelve#3]
**Issue:**

Currently, the keys of dictionaries aren't sorted alphabetically. This would greatly help with editing them, as finding keys can be time-consuming.

**Screenshots:**

![image](https://github.com/user-attachments/assets/7fcebf86-9f4c-4a53-9a1f-ebe80324de58)

![image](https://github.com/user-attachments/assets/a40735aa-89a9-4e80-8b8e-d79b30d31494)

**Comment by pinehappi** [comment]
Thanks for the report! The patch for this is available here: https://create.roblox.com/store/asset/17652185888/DataDelve-Canary-easy-free-datastore-editor
